#!/bin/bash

set -e

cd ./spec/dummy/

find ./db/migrate -type f -exec rm -i {} \; || true

bundle install
bundle exec rake db:test:purge

./bin/rails g smailer:migration

bundle exec rake db:migrate RAILS_ENV=test
